server:
  port: 8882
spring:
  application:
    name: biz-2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: admin
    password: Admin123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka
    enabled: false

