server:
  port: 8881
  servlet:
    context-path: /biz-1
      
spring:
  application:
    name: biz-1
  redis:
    host: localhost
    port: 6379 
    timeout: 3000 #连接超时
    jedis:
      pool:
        max-active: 100 #连接池最大连接数
        max-wait: 3000 #连接池最大的阻塞等待时间
        max-idle: 20 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
        
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: C##CLOUD
    password: Admin123

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka

