server:
  port: 8883
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka
